### PR TITLE
Backport to 1.19.2

### PR DESCRIPTION
**Pull request by CCr4ft3r**
Hi there :)

finally I found some time to backport it. I would really appreciate it if you would accept this pull request 
and publish the version on CurseForge :)

I will also try to backport it to 1.18.2 next week.

Sincerely CCr4ft3r

### CODE REVIEW

**Comment by Crendgrim** [comment]
All of the useless whitespace changes make the patch quite a lot larger than it has to be, but I'll accept it like this. I'll test things a bit and then push it. Thank you for the work!

**Comment by CCr4ft3r** [comment]
oh okay - that's probably because of the default IntelliJ file formatter.

**Comment by Crendgrim** [comment]
Yeah, it sadly messed with the entire AutoYacl file; and this patch breaks yacl support on Fabric.

**Comment by Crendgrim** [comment]
Ah, I see what the problem is. YACL-for-1.19.2 only has version 2.2.0, but I rely on behaviour introduced in 2.4.1. Your blind changes that made it compile didn't work. Hmm.

It would probably be a good idea to move back to ClothConfig for 1.19.2 (and especially earlier, if you still want to port to 1.18).

**Comment by CCr4ft3r** [comment]
ok, I will give it a try

**Comment by Crendgrim** [comment]
I'm working on it already

**Comment by Crendgrim** [comment]
I moved to Cloth-Config, both making Fabric work and giving a config UI under Forge :)

However, I was too stupid to understand how to accept this PR to go into a new branch, so I had to do it manually. I'm too stupid for GitHub. It's in the 1.19.2 branch here now, though!

Thank you so much for working on this! I pushed version 4.3+1.19.2 for both Fabric & Forge :)

**Comment by CCr4ft3r** [comment]
Great - Thx 👍 Yeah, I think GitHub does not provide any feature to push pull requests into a new branch 😐 A common way is that the repo owner creates a new branch based on the target branch and after reviewing the owner can edit the pull request to change the target branch to the new created one.

**Pull request closed without merging**
